project_id = "iqculanjeijiqenzsvhc"

[functions.generate-devotional]
verify_jwt = false

[functions.generate-sermon]
verify_jwt = false

[functions.define-word]
verify_jwt = false

[functions.find-scripture]
verify_jwt = false
